spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password: sa
  h2:
    console:
      enabled: true
  flyway:
    url: jdbc:h2:mem:testdb
    baseline-on-migrate: true
    user: sa
    password: sa

management:
  security:
    enabled: true
  endpoints:
    enabled-by-default: false
    health:
      sensitive: false
    web:
      exposure:
        include: "test,prometheus,health,info,metrics"
  endpoint:
    shutdown:
      enabled: true
    health:
      enabled: true
      show-details: "ALWAYS"
    info:
      enabled: true
    metrics:
      enabled: true
    prometheus:
      enabled: true

jwt:
  token:
    secret: testObj
    expired: 3600000

app:
  message: "Dev profile"